FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS restore
WORKDIR /src
COPY ./Ensek.PeteForrest.Api.csproj ./Ensek.PeteForrest.Api.csproj
RUN dotnet restore "./Ensek.PeteForrest.Api.csproj"

FROM restore as publish
WORKDIR /src
COPY . .
RUN dotnet publish "./Ensek.PeteForrest.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Ensek.PeteForrest.Api.dll"]